### ISSUE TITLE
panic: flag "-db" begins with -

### ISSUE THREAD

**Issue by JoyceBabu** [ruhnet/google-squawk#1]
Program panics with error 

> flag "-db" begins with -

Go no longer allows flags with double hyphens.

https://github.com/golang/go/issues/41792

**Comment by ruhnet** [comment]
Ah, thank you for finding this---I will investigate a bit and perform the necessary modifications.

**Comment by JoyceBabu** [comment]
The problem is on line 48

https://github.com/ruhnet/google-squawk/blob/master/main.go#L48

**Comment by ruhnet** [comment]
Yes---that line was of course the offending line, but I wanted to find out why I had set that option as having a double hyphen. There was a reason originally, but unfortunately I don't have any notes of it. So anyway it should be fine now. Thanks again for catching that. :)
